### ISSUE TITLE
Definir teclas de atalhos que vão ser usadas na tela de nova venda

### ISSUE THREAD

**Issue by pablomariz** [duzz-system/Duzz-Commercial#169]

**Comment by Jonasdart** [comment]
[Shift + Espaço] - abrir modal pesquisa
[Shift + C] - Selecionar cliente
[Shift + D] - Selecionar promo
[Shift + setas] - controlar juros
[Shift + del] - remover o produto em destaque da tabela
[Enter] confirmar
