### ISSUE TITLE
Corrigir bug no campo observação

### ISSUE THREAD

**Issue by pablomariz** [duzz-system/Duzz-Commercial#175]
Corrigir bug no campo observação, quando envia nova venda e passa algum valor no campo descrição, ocorre erro

**Comment by Jonasdart** [comment]
https://github.com/duzz-system/Duzz-Commercial/blob/a8a0be3b5c57db101549bd8512ab9a7940b59c95/resources/sales/models/__init__.py#L80

Adicionar validação no models.body_validate:

```
{
    'observation': {
        'required': False,
        'type': str
    }
}
```
