### ISSUE TITLE
Resource de venda

### ISSUE THREAD

**Issue by pablomariz** [duzz-system/Duzz-Commercial#178]

**Comment by pablomariz** [comment]
Campo observação na tela de de nova venda

**Comment by Jonasdart** [comment]
https://github.com/duzz-system/Duzz-Commercial/blob/a8a0be3b5c57db101549bd8512ab9a7940b59c95/resources/sales/models/__init__.py#L80

Adicionar validação no models.body_validate:

```
{
    'observation': {
        'required': False,
        'type': str
    }
}
```

**Comment by Jonasdart** [comment]
Problema sendo tratado na solicitação #175
