### ISSUE TITLE
Gestão - Contas à pagar

### ISSUE THREAD

**Issue by Jonasdart** [duzz-system/Duzz-Commercial#219]
Desenvolver tela de procura e pagamento de contas pendentes.

Local ->

Gestão
└── Contas à pagar

**Comment by henriquefons** [comment]
Resource: bills-to-pay
patch -> pagar
get -> pesquisar

link que leva para a tela de detalhes do item que gerou a conta

**Comment by Jonasdart** [comment]
Ponto de atenção:

Necessário passar para o @henriquefons os textos presentes nos informativos:

- Pagamento maior que o restante:
 - Mensagem de alerta ao colocar valor no input maior que o restante a ser pago
 - Mensagem de verificação do modal de confirmação

- Encerrar a conta antes de finalizar o pagamento total:
  - Mensagem para aparecer no modal de confirmação
  - Texto para a pessoa redigitar como confirmação
