### ISSUE TITLE
Tela de cadastro de custos

### ISSUE THREAD

**Issue by pablomariz** [duzz-system/Duzz-Commercial#237]

**Comment by Jonasdart** [comment]
Desenvolvimento do front parado aguardando correção do cadastro de custos

**Comment by Jonasdart** [comment]
Pendências:

- Pesquisa por itens criados por sistema/ usuário. 
  - Solução: Campo bySystem adicionado ao retorno dos custos
- Solicitação de pagamento, informando data de vencimento, fornecedor e titulo da notificação.
  - Solução: Campos `supplier`, `dueDate` e `notificationTitle` adicionados à rota Patch
- Criação de custos com metadados:
  - Estrutura de json fixa:

```
{
                'referenceTable': 5,
                'referenceId': 'self',
                'type': 'SINGLE',
                'recurrent': {
                    'activate': False,
                    'frequency': None
                },
                'supplier': supplier
            }
```

`referenceTable` e `referenceId`: Caso o usuário queira relacionar o custo com algum item do sistema.
`type`: SINGLE quando só puder solicitar um pagamento por vez. MULTI quando puder ter mais de uma conta à pagar do mesmo custo
`recurrent`: Frequência de solicitação automatica de pagamento do custo. (DEIXAR COMO DESATIVADO POR PADRÃO, POR ENQUANTO).
`supplier`: Caso haja um fornecedor específico que raramente será alterado.
